skip_dirs:
    - "__pycache__"
    - "node_modules"
    - "venv"
    - ".venv"
    - "*venv"
    - ".idea"
    - "*idea"
    - ".vscode"
    - "*vscode"
    - ".qodo"
    - "*qodo"
    - "*pytest_cache"
    - ".pytest_cache"
    - "htmlcov"
    - "auto_code_documenter"
    - "external_data"
    - "data"
    - "historical_data"
    - "actual_data"
    - "_freeze"
    - "visualisation"
    - "docs_quarto"
    - ".quarto"


skip_patterns:
    - "*.pyc"
    - "*.pyo"
    - "*.so"
    - "*.o"
    - "*.jpg"
    - "*.jpeg"
    - "*.png"
    - "*.gif"
    - "*.pdf"
    - "*.bin"
    - "*.exe"
    - "*.dll"
    - "*.class"
    - ".DS_Store"
    - ".gitignore"
    - "*.pkl"
    - "*.pyd"
    - "*.dylib"
    - "coverage.*"
    - "*.xl*"
    - "*.html"
    - "*.ipynb"
    - "*.svg"
    - "*.drawio"
    - "*event_log.csv"
    - "*run_results.csv"
    - "*all_results.csv"
    - "*call_df.csv"
    - "*log*.txt"
    - "*LOG*.txt"
    - ".gitkeep"
    - "*.gitkeep*"
    - "tests/**/*.csv"
    - "*_UNUSED*"
    - "__init__"
    - "*__init__*"
    - "*distribution_data/archive/*"
    - "*quarto_ipynb*"
    - "*.wav"
    - "*.js"
    - "air_ambulance_des_docs/.quarto/*"
    - "air_ambulance_des_docs/reference/*"
    - "air_ambulance_des.egg-info/*"
