project:
  type: website
  output-dir: ../docs_quarto
  pre-render:
    - sync_docs.py

website:
  title: "Air Ambulance Simulation"
  description: "Documentation for the vidigi pathway animation package"

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml

quartodoc:
  dir: reference
  out_index: index.qmd
  # the name used to import the package you want to create reference docs for
  package: air_ambulance_des
  # write sidebar data to this file
  sidebar:
    file: "_sidebar.yml"
    style: docked
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/RichardPilbery/DAA_DES
            target: _blank
          - text: Report a Bug
            href:  https://github.com/RichardPilbery/DAA_DES/issues
            target: _blank

    search: true
    title: "Air Ambulance Simulation"
    subtitle: "Opreational Modelling for Air Ambulance Services"
    collapse-level: 2
    contents:
      - file: index.qmd
        text: "Introduction"
      - file: readme.qmd
        text: "Project Overview"
      - section: "Class and Function Overview"
        contents:
          - "{{ contents }}"
      - section: "Model Checklists"
        contents:
        - text: "STARS"
          href: STARS.qmd
        - text: "STRESS-DES"
          href: STRESS_DES.qmd
      - section: "Package Details"
        contents:
        - text: "Licence"
          href: licence.qmd
        - text: "Contributor Code of Conduct"
          href: code_of_conduct.qmd
        - text: "Citing this Work"
          href: citation_details.qmd

  sections:
    - title: Model Component Classes
      desc: ""
      contents:
        - class_ambulance.Ambulance
        - class_hems.HEMS
        - class_patient.Patient
    - title: Resource Availability
      desc: ""
      contents:
        - class_hems_availability.ResourceAllocationReason
        - class_hems_availability.HEMSAvailability

    - title: Data Fitting and Preparation
      desc: ""
      contents:
        - distribution_fit_utils.DistributionFitUtils

    - title: Simulation Model
      desc: ""
      contents:
        - des_hems.DES_HEMS

    - title: Model Running
      desc: ""
      contents:
        - des_parallel_process.runSim
        - des_parallel_process.parallelProcessJoblib

    - title: Results
      desc: ""
      contents:
        - class_simulation_inputs.SimulationInputs
        - class_simulation_trial_results.TrialResults

    - title: Helpers
      desc: ""
      contents:
        - des_parallel_process.write_run_params
        - des_parallel_process.collateRunResults



format:
  html:
    grid:
      sidebar-width: 325px
      body-width: 1200px
      margin-width: 250px
      gutter-width: 1.5rem
    execute:
      freeze: auto
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
